name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: yarn run e2e:generate:personas && yarn build

      - name: Save build
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .next

      - name: Save perrsonas
        uses: actions/upload-artifact@v3
        with:
          name: personas
          if-no-files-found: error
          path: cypress/e2e/integration/test-completion

  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: cypress/browsers:latest
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    name: Testing e2e in worker ${{ matrix.containers }}
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Download the personas
        uses: actions/download-artifact@v3
        with:
          name: personas

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Test - e2e [${{ env.MODE }}]
        uses: cypress-io/github-action@v5.6.1
        with:
          browser: chrome
          parallel: true
          record: true
          group: 'Test - e2e'
          spec: cypress/e2e/integration/**/*.cy.js
          start: yarn start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
